=== alwaystudios/recipe-bible-sdk/src/recipe-schema.json
{
  "$ref": "#/definitions/Recipe",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Ingredient": {
      "additionalProperties": false,
      "properties": {
        "measure": {
          "$ref": "#/definitions/Measure"
        },
        "name": {
          "type": "string"
        },
        "quantity": {
          "type": ["string", "number"]
        }
      },
      "required": ["name", "measure", "quantity"],
      "type": "object"
    },
    "Measure": {
      "enum": ["qty", "g", "ml", "tsp", "tbsp", "handful", "cup", "slice(s)", "kg"],
      "type": "string"
    },
    "Nutrition": {
      "additionalProperties": false,
      "properties": {
        "calories": {
          "type": "string"
        },
        "carbs": {
          "type": "string"
        },
        "fat": {
          "type": "string"
        },
        "fibre": {
          "type": "string"
        },
        "protein": {
          "type": "string"
        },
        "salt": {
          "type": "string"
        },
        "satFat": {
          "type": "string"
        },
        "sugar": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Recipe": {
      "additionalProperties": false,
      "properties": {
        "categories": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "cookingTime": {
          "type": "string"
        },
        "id": {
          "type": "number"
        },
        "imgSrc": {
          "type": "string"
        },
        "ingredients": {
          "items": {
            "$ref": "#/definitions/Ingredient"
          },
          "type": "array"
        },
        "metadata": {
          "$ref": "#/definitions/RecipeMetadata"
        },
        "nutrition": {
          "$ref": "#/definitions/Nutrition"
        },
        "servings": {
          "type": "number"
        },
        "steps": {
          "items": {
            "$ref": "#/definitions/Step"
          },
          "type": "array"
        },
        "story": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      },
      "required": [
        "categories",
        "cookingTime",
        "imgSrc",
        "ingredients",
        "metadata",
        "nutrition",
        "servings",
        "steps"
      ],
      "type": "object"
    },
    "RecipeMetadata": {
      "additionalProperties": false,
      "properties": {
        "focused": {
          "type": "boolean"
        },
        "published": {
          "type": "boolean"
        },
        "reviewed": {
          "type": "boolean"
        }
      },
      "required": ["focused", "reviewed", "published"],
      "type": "object"
    },
    "Step": {
      "additionalProperties": false,
      "properties": {
        "imgSrc": {
          "type": "string"
        },
        "step": {
          "type": "string"
        }
      },
      "required": ["step"],
      "type": "object"
    }
  }
}

=== alwaystudios/recipe-bible-sdk/src/test/super-tasty-pasta-bolognese.json
{
  "categories": ["Meat", "Pasta"],
  "metadata": {
    "focused": true,
    "published": true,
    "reviewed": false
  },
  "servings": 2,
  "cookingTime": "25 mins",
  "story": "This is the first dish of the day, by Gary",
  "imgSrc": "spagBol.jpg",
  "nutrition": {
    "fat": "26g",
    "salt": "4g",
    "carbs": "86g",
    "fibre": "12g",
    "sugar": "20g",
    "protein": "46g",
    "satFat": "12g",
    "calories": "775kcal"
  },
  "steps": [
    {
      "step": "Boil a kettle, finely chop onion, carrot and garlic",
      "imgSrc": "step.jpg"
    },
    {
      "step": "Fry the onion and carrot with a pinch of salt for 4 mins",
      "imgSrc": "step.jpg"
    },
    { "step": "Add the mince beef and cook for further 4 mins", "imgSrc": "step.jpg" },
    {
      "step": "While the beef is cooking add the boiled water to a pan and cook the pasta for 10 mins",
      "imgSrc": "step.jpg"
    },
    {
      "step": "Dissolve the beef stock cube with the soy sauce in 200ml boiled water",
      "imgSrc": "step.jpg"
    },
    {
      "step": "Add the garlic, tomato paste, dried basil, dried oregano, stock mix to the pan",
      "imgSrc": "step.jpg"
    },
    { "step": "Season with pepper and cook for further 4 mins", "imgSrc": "step.jpg" },
    {
      "step": "Mix the pasta into the pan and serve with grated cheese",
      "imgSrc": "step.jpg"
    }
  ],
  "ingredients": [
    {
      "name": "brown-onion",
      "measure": "qty",
      "quantity": "1"
    },
    {
      "name": "carrot",
      "measure": "qty",
      "quantity": "1"
    },
    {
      "name": "garlic-clove",
      "measure": "qty",
      "quantity": "2"
    },
    {
      "name": "soy-sauce",
      "measure": "ml",
      "quantity": "8"
    },
    {
      "name": "dried-oregano",
      "measure": "tsp",
      "quantity": "1"
    },
    {
      "name": "dried-basil",
      "measure": "tsp",
      "quantity": "1"
    },
    {
      "name": "beef-stock-cube",
      "measure": "qty",
      "quantity": "1"
    },
    {
      "name": "tomato-paste",
      "measure": "g",
      "quantity": "18"
    },
    {
      "name": "cheddar",
      "measure": "g",
      "quantity": "40"
    },
    {
      "name": "pasta",
      "measure": "g",
      "quantity": "180"
    },
    {
      "name": "can-tinned-tomato",
      "measure": "qty",
      "quantity": "1"
    },
    {
      "name": "minced-beef",
      "measure": "g",
      "quantity": "250"
    }
  ]
}
